# Adaptive Trading System Configuration
# Configuration for the intelligent adaptive trading system

# =============================================================================
# Market Condition Detection Thresholds
# =============================================================================
market_conditions:
  volatility_thresholds:
    elevated_volatility: 0.01    # 1% price change
    high_volatility: 0.02        # 2% price change
    extreme_volatility: 0.05     # 5% price change
  
  spread_thresholds:
    normal_spread: 1.5           # 1.5 pips
    wide_spread: 3.0             # 3.0 pips
    extreme_spread: 5.0          # 5.0 pips
  
  margin_thresholds:
    warning_level: 0.7           # 70% margin usage
    critical_level: 0.8          # 80% margin usage
    emergency_level: 0.9         # 90% margin usage
  
  correlation_thresholds:
    strong_correlation: 0.8      # 80% correlation
    weak_correlation: 0.3        # 30% correlation
    broken_correlation: 0.1      # 10% correlation

# =============================================================================
# Strategy-Specific Adaptations
# =============================================================================
strategy_adaptations:
  PRIMARY:  # Ultra Strict Forex
    base_risk:
      position_size_multiplier: 1.0
      stop_loss_adjustment: 1.0
      take_profit_adjustment: 1.0
      max_positions: 5
      max_margin_usage: 0.8
      daily_trade_limit: 50
    
    high_volatility:
      position_size_multiplier: 0.5
      stop_loss_adjustment: 1.5
      max_positions: 3
      max_margin_usage: 0.6
      trade_frequency: "reduced"
    
    central_bank_events:
      position_size_multiplier: 0.3
      trade_frequency: "paused"
      pause_duration_hours: 4
      max_margin_usage: 0.5
    
    momentum_reversal:
      position_size_multiplier: 0.7
      stop_loss_adjustment: 0.8
      close_percentage: 0.3

  GOLD:  # Gold Scalping
    base_risk:
      position_size_multiplier: 1.0
      stop_loss_adjustment: 1.0
      take_profit_adjustment: 1.0
      max_positions: 3
      max_margin_usage: 0.6
      daily_trade_limit: 100
    
    high_volatility:
      position_size_multiplier: 0.25  # Extra aggressive for gold
      stop_loss_adjustment: 2.0       # Much wider stops
      max_positions: 2
      max_margin_usage: 0.4
      trade_frequency: "minimal"
    
    central_bank_events:
      position_size_multiplier: 0.1
      trade_frequency: "paused"
      pause_duration_hours: 6
      max_margin_usage: 0.3
    
    momentum_reversal:
      position_size_multiplier: 0.5
      stop_loss_adjustment: 1.5
      close_percentage: 0.5

  ALPHA:  # Momentum Trading
    base_risk:
      position_size_multiplier: 1.0
      stop_loss_adjustment: 1.0
      take_profit_adjustment: 1.0
      max_positions: 7
      max_margin_usage: 0.8
      daily_trade_limit: 30
    
    high_volatility:
      position_size_multiplier: 0.6
      stop_loss_adjustment: 1.3
      max_positions: 4
      max_margin_usage: 0.6
      trade_frequency: "reduced"
    
    central_bank_events:
      position_size_multiplier: 0.4
      trade_frequency: "paused"
      pause_duration_hours: 3
      max_margin_usage: 0.5
    
    momentum_reversal:
      position_size_multiplier: 0.3  # Fast adaptation
      stop_loss_adjustment: 0.7      # Tighter stops
      close_percentage: 0.4

# =============================================================================
# Monitoring Configuration
# =============================================================================
monitoring:
  update_interval: 30              # Check every 30 seconds
  price_history_length: 100        # Keep last 100 price points
  volatility_history_length: 50    # Keep last 50 volatility readings
  
  instruments:
    - "EUR_USD"
    - "GBP_USD" 
    - "USD_JPY"
    - "XAU_USD"
    - "AUD_USD"
    - "USD_CAD"
    - "NZD_USD"
    - "USD_CHF"
  
  adaptation_cooldown: 300         # 5 minutes between adaptations
  report_interval: 3600           # 1 hour between reports

# =============================================================================
# Alert Configuration
# =============================================================================
alerts:
  telegram:
    enabled: true
    send_startup_notification: true
    send_adaptation_alerts: true
    send_daily_reports: true
    send_error_alerts: true
  
  email:
    enabled: false
    smtp_server: ""
    smtp_port: 587
    username: ""
    password: ""
    recipients: []

# =============================================================================
# Emergency Controls
# =============================================================================
emergency_controls:
  max_daily_loss_percent: 5.0      # 5% daily loss limit
  max_position_size_percent: 2.0   # 2% max position size
  force_close_margin_percent: 0.95 # Force close at 95% margin
  
  automatic_shutdown:
    enabled: true
    conditions:
      - "portfolio_loss_exceeds_10_percent"
      - "margin_usage_exceeds_95_percent"
      - "system_error_rate_high"

# =============================================================================
# Learning and Analytics
# =============================================================================
learning:
  save_learning_data: true
  data_retention_days: 30
  pattern_recognition:
    enabled: true
    lookback_period_hours: 24
    min_pattern_confidence: 0.7
  
  performance_tracking:
    enabled: true
    track_adaptations: true
    track_market_conditions: true
    track_strategy_performance: true

# =============================================================================
# Development and Testing
# =============================================================================
development:
  debug_mode: false
  verbose_logging: false
  test_mode: false
  mock_trading: false
  
  simulation:
    enabled: false
    start_date: "2024-01-01"
    end_date: "2024-12-31"
    initial_balance: 10000

