# Google Cloud Trading System - F1 FREE TIER OPTIMIZED
# Optimized for maximum cost savings using Google Cloud Free Tier

# =============================================================================
# Runtime Configuration
# =============================================================================
runtime: python311

# =============================================================================
# Service Configuration
# =============================================================================
service: default
entrypoint: python main.py

# =============================================================================
# F1 FREE TIER OPTIMIZATION
# =============================================================================
automatic_scaling:
  # FREE TIER: 28 instance-hours per day (F1 only)
  min_instances: 1
  max_instances: 1
  
  # Optimized for F1 efficiency
  target_cpu_utilization: 0.9
  target_throughput_utilization: 0.9
  
  # Optimized response times for F1
  min_pending_latency: 10ms
  max_pending_latency: 100ms

# =============================================================================
# Instance Configuration - F1 FREE TIER
# =============================================================================
instance_class: F1

# =============================================================================
# Environment Variables - F1 OPTIMIZED
# =============================================================================
env_variables:
  # Flask Configuration
  FLASK_ENV: production
  FLASK_DEBUG: "False"
  PORT: "8080"
  
  # Safe defaults (override via Secret Manager or Cloud Console)
  SYSTEM_MODE: "verification"
  ENABLE_LIVE_TRADING: "0"
  ENABLE_MARKET_DATA: "0"
  ENABLE_SOCKETIO: "0"
  ENABLE_SCHEDULER: "0"

# =============================================================================
# Handlers Configuration
# =============================================================================
handlers:
  # Static files handler
  - url: /static
    static_dir: static
    secure: always
    
  # Task endpoints
  - url: /tasks/full_scan
    script: auto
    secure: always
  - url: /tasks/full_scan_public
    script: auto
    secure: always
  - url: /tasks/progressive_scan
    script: auto
    secure: always
  - url: /tasks/.*
    script: auto
    secure: always
    login: admin
  - url: /.*
    script: auto
    secure: always

# =============================================================================
# Network Configuration - F1 OPTIMIZED
# =============================================================================
network:
  # Session affinity for F1
  session_affinity: true
  
  # Forwarded port configuration
  forwarded_ports:
    - 8080

# =============================================================================
# Health Check Configuration - F1 OPTIMIZED
# =============================================================================
readiness_check:
  path: "/api/health"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 5
  success_threshold: 2
  app_start_timeout_sec: 600

liveness_check:
  path: "/api/health"
  check_interval_sec: 60
  timeout_sec: 10
  failure_threshold: 5
  success_threshold: 2

# =============================================================================
# Resource Limits - F1 FREE TIER
# =============================================================================
resources:
  cpu: 0.2
  memory_gb: 0.2
  disk_size_gb: 5

# =============================================================================
# Beta Features
# =============================================================================
beta_settings:
  # Enable Cloud Build for automatic deployments
  cloud_build: true
