# Google Cloud Trading System - F1 FREE TIER OPTIMIZED
# Optimized for maximum cost savings using Google Cloud Free Tier

# =============================================================================
# Runtime Configuration
# =============================================================================
runtime: python311

# =============================================================================
# Service Configuration
# =============================================================================
service: default
entrypoint: python main.py

# =============================================================================
# F1 FREE TIER OPTIMIZATION
# =============================================================================
automatic_scaling:
  # FREE TIER: 28 instance-hours per day (F1 only)
  min_instances: 1
  max_instances: 1
  
  # Optimized for F1 efficiency
  target_cpu_utilization: 0.9
  target_throughput_utilization: 0.9
  
  # Optimized response times for F1
  min_pending_latency: 10ms
  max_pending_latency: 100ms

# =============================================================================
# Instance Configuration - F1 FREE TIER
# =============================================================================
instance_class: F1

# =============================================================================
# Environment Variables - F1 OPTIMIZED
# =============================================================================
env_variables:
  # Flask Configuration
  FLASK_ENV: production
  FLASK_DEBUG: "False"
  PORT: "8080"
  
  # OANDA API Configuration
  OANDA_API_KEY: "c01de9eb4d793c945ea0fcbb0620cc4e-d0c62eb93ed53e8db5a709089460794a"
  OANDA_ENVIRONMENT: "practice"
  OANDA_BASE_URL: "https://api-fxpractice.oanda.com"
  
  # F1 FREE TIER OPTIMIZATION
  F1_FREE_TIER_MODE: "true"
  ULTRA_OPTIMIZED_RESOURCE_USAGE: "true"
  MINIMAL_MEMORY_USAGE: "true"
  
  # Strategy Groups - All 3 on F1 instance
  GROUP_1_ACCOUNT: "101-004-30719775-008"
  GROUP_2_ACCOUNT: "101-004-30719775-007"
  GROUP_3_ACCOUNT: "101-004-30719775-006"
  
  # Account Configuration
  OANDA_ACCOUNT_ID: "101-004-30719775-008"
  PRIMARY_ACCOUNT: "101-004-30719775-008"
  GOLD_SCALP_ACCOUNT: "101-004-30719775-007"
  STRATEGY_ALPHA_ACCOUNT: "101-004-30719775-006"
  
  # Top 3 Optimized Strategies
  TOP_STRATEGY_1_ACCOUNT: "101-004-30719775-008"
  TOP_STRATEGY_2_ACCOUNT: "101-004-30719775-007"
  TOP_STRATEGY_3_ACCOUNT: "101-004-30719775-006"
  
  # Strategy Mapping
  PRIMARY_STRATEGY: "gbp_usd_5m_strategy_rank_1"
  GOLD_SCALP_STRATEGY: "gbp_usd_5m_strategy_rank_2"
  STRATEGY_ALPHA_STRATEGY: "gbp_usd_5m_strategy_rank_3"
  
  # Telegram Configuration
  TELEGRAM_TOKEN: "7248728383:AAEE7lkAAIUXBcK9iTPR5NIeTq3Aqbyx6IU"
  TELEGRAM_CHAT_ID: "6100678501"
  
  # Google Cloud Configuration
  GOOGLE_CLOUD_PROJECT: "ai-quant-trading"
  GOOGLE_CLOUD_REGION: "us-central1"
  
  # F1 OPTIMIZED Risk Management
  PRIMARY_MAX_RISK_PER_TRADE: "0.015"
  PRIMARY_MAX_PORTFOLIO_RISK: "0.6"
  PRIMARY_MAX_POSITIONS: "3"
  PRIMARY_DAILY_TRADE_LIMIT: "8"
  
  GOLD_MAX_RISK_PER_TRADE: "0.01"
  GOLD_MAX_PORTFOLIO_RISK: "0.6"
  GOLD_MAX_POSITIONS: "2"
  GOLD_DAILY_TRADE_LIMIT: "6"
  
  ALPHA_MAX_RISK_PER_TRADE: "0.02"
  ALPHA_MAX_PORTFOLIO_RISK: "0.6"
  ALPHA_MAX_POSITIONS: "4"
  ALPHA_DAILY_TRADE_LIMIT: "8"
  
  # Global Risk Settings
  MAX_CORRELATION_RISK: "0.6"
  POSITION_SIZING_METHOD: "risk_based"
  POSITION_SIZE_MULTIPLIER: "0.3"
  FORCED_TRADING_MODE: "disabled"      # DISABLED OCT 16: No forced trades!
  MIN_TRADES_TODAY: "0"                 # ZERO forced trades - quality only!
  
  # FTMO Challenge Settings
  FTMO_MODE: "enabled"
  FTMO_PHASE: "1"
  FTMO_ACCOUNT_SIZE: "100000"
  FTMO_MAX_DAILY_DRAWDOWN: "0.05"
  FTMO_MAX_TOTAL_DRAWDOWN: "0.10"
  FTMO_PROFIT_TARGET: "0.10"
  FTMO_MAX_RISK_PER_TRADE: "0.005"
  FTMO_MAX_DAILY_TRADES: "5"
  FTMO_MAX_CONCURRENT_POSITIONS: "2"
  FTMO_MIN_RISK_REWARD: "2.0"
  
  # Data Validation Settings
  MAX_DATA_AGE_SECONDS: "600"
  MIN_CONFIDENCE_THRESHOLD: "0.6"
  REQUIRE_LIVE_DATA: "True"
  
  # ADAPTIVE MARKET SYSTEM - ENABLED OCT 10, 2025
  ADAPTIVE_SYSTEM_ENABLED: "true"
  ADAPTIVE_CONFIDENCE_FLOOR: "0.60"
  ADAPTIVE_CONFIDENCE_CEILING: "0.80"
  ADAPTIVE_CONFIDENCE_OPTIMAL: "0.65"
  ADAPTIVE_RISK_MIN_MULTIPLIER: "0.5"
  ADAPTIVE_RISK_MAX_MULTIPLIER: "2.0"
  
  # Trading System Configuration
  MOCK_TRADING: "False"
  DEVELOPMENT_MODE: "False"
  
  # Logging Configuration
  LOG_LEVEL: "WARNING"
  ENABLE_STRUCTURED_LOGGING: "False"
  
  # F1 OPTIMIZED Performance Settings
  DASHBOARD_UPDATE_INTERVAL: "60"
  MARKET_DATA_UPDATE_INTERVAL: "30"
  SYSTEM_STATUS_CHECK_INTERVAL: "120"
  
  # Security Settings
  API_RATE_LIMIT: "50"
  API_RATE_WINDOW: "60"
  CORS_ORIGINS: "*"
  
  # News API Configuration
  ALPHA_VANTAGE_API_KEY: "LSBZJ73J9W1G8FWB"
  MARKETAUX_API_KEY: "qL23wrqpBdU908DrznhIpfINVOgDg4bPmpKzQfW2"
  NEWSDATA_API_KEY: "pub_1234567890abcdef"
  NEWSAPI_KEY: "your_newsapi_key"
  
  # News Integration Settings - F1 OPTIMIZED
  NEWS_TRADING_ENABLED: "True"
  HIGH_IMPACT_PAUSE: "True"
  NEGATIVE_SENTIMENT_THRESHOLD: "-0.4"
  POSITIVE_SENTIMENT_THRESHOLD: "0.4"
  NEWS_CONFIDENCE_THRESHOLD: "0.7"
  
  # News API Performance - REDUCED for F1
  NEWS_COLLECTION_INTERVAL: "600"
  CACHE_DEFAULT_TTL: "30"
  API_REQUEST_TIMEOUT: "60"

  # AI Assistant Configuration - F1 OPTIMIZED
  AI_ASSISTANT_ENABLED: "true"
  AI_MODEL_PROVIDER: "demo"
  AI_RATE_LIMIT_PER_MINUTE: "5"
  AI_REQUIRE_LIVE_CONFIRMATION: "true"
  
  # Live actions toggle
  ALLOW_LIVE_ACTIONS: "true"
  
  # Trading configuration - FULL PRODUCTION MODE
  WEEKEND_MODE: "false"
  TRADING_DISABLED: "false"
  SIGNAL_GENERATION: "enabled"
  FORCE_TRADING_DISABLED: "false"
  AUTO_TRADING_ENABLED: "true"
  ENABLE_CANDLE_SCANNER: "true"
  MAX_TRADES_PER_ACCOUNT: "100"
  REQUIRE_EMA_CROSSOVER: "true"
  REQUIRE_RSI_CONFIRMATION: "true"
  
  # Account Instrument Mappings - CRITICAL FOR CORRECT TRADING
  ACCOUNT_001_INSTRUMENTS: "XAU_USD"
  ACCOUNT_006_INSTRUMENTS: "EUR_JPY,USD_CAD"
  ACCOUNT_007_INSTRUMENTS: "GBP_USD,XAU_USD"
  ACCOUNT_008_INSTRUMENTS: "GBP_USD,NZD_USD,XAU_USD"
  ACCOUNT_011_INSTRUMENTS: "EUR_USD,GBP_USD,USD_JPY,AUD_USD,USD_CAD"

  # Secure manual scan trigger token
  SCAN_TRIGGER_TOKEN: "scan_7d8f5c5f8b2a4a8f"
  
  # =========================================================================
  # RISK MANAGEMENT SETTINGS - LESSONS FROM OCT 6, 2025
  # =========================================================================
  MAX_POSITIONS: "15"
  MAX_MARGIN_PCT: "40.0"
  MIN_SIGNAL_STRENGTH: "0.7"
  MAX_SPREAD_PIPS: "3.0"
  MAX_CORRELATED: "2"
  ENABLE_TIME_FILTER: "true"
  ENABLE_CORRELATION_CHECK: "true"
  ENABLE_BREAKEVEN_STOPS: "true"

# =============================================================================
# Handlers Configuration
# =============================================================================
handlers:
  # Static files handler
  - url: /static
    static_dir: static
    secure: always
    
  # Task endpoints
  - url: /tasks/full_scan
    script: auto
    secure: always
  - url: /tasks/full_scan_public
    script: auto
    secure: always
  - url: /tasks/progressive_scan
    script: auto
    secure: always
  - url: /tasks/.*
    script: auto
    secure: always
    login: admin
  - url: /.*
    script: auto
    secure: always

# =============================================================================
# Network Configuration - F1 OPTIMIZED
# =============================================================================
network:
  # Session affinity for F1
  session_affinity: true
  
  # Forwarded port configuration
  forwarded_ports:
    - 8080

# =============================================================================
# Health Check Configuration - F1 OPTIMIZED
# =============================================================================
readiness_check:
  path: "/api/health"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 5
  success_threshold: 2
  app_start_timeout_sec: 600

liveness_check:
  path: "/api/health"
  check_interval_sec: 60
  timeout_sec: 10
  failure_threshold: 5
  success_threshold: 2

# =============================================================================
# Resource Limits - F1 FREE TIER
# =============================================================================
resources:
  cpu: 0.2
  memory_gb: 0.2
  disk_size_gb: 5

# =============================================================================
# Beta Features
# =============================================================================
beta_settings:
  # Enable Cloud Build for automatic deployments
  cloud_build: true
