# =============================================================================
# STRATEGY CONFIGURATION MASTER - SINGLE SOURCE OF TRUTH
# =============================================================================
# This is the ONLY file that defines strategy configuration
# All other files must reference this file
# Last Updated: 2025-10-24
# =============================================================================

strategies:
  momentum_trading:
    name: "Momentum Trading"
    description: "Momentum-based entries with EMA crossover"
    instruments: ["EUR_USD", "GBP_USD", "USD_JPY", "AUD_USD", "XAU_USD"]
    risk_settings:
      max_risk_per_trade: 0.02
      max_portfolio_risk: 0.50
      daily_trade_limit: 50
      max_positions: 3
    target_performance:
      sharpe: 2.5
      win_rate: 60.0
      annual_return: 100.0

  zero_drawdown:
    name: "Zero Drawdown"
    description: "Conservative trading with maximum protection"
    instruments: ["EUR_USD", "GBP_USD", "XAU_USD"]
    risk_settings:
      max_risk_per_trade: 0.01
      max_portfolio_risk: 0.30
      daily_trade_limit: 30
      max_positions: 2
    target_performance:
      sharpe: 6.12
      win_rate: 53.6
      annual_return: 2244.0

  high_win_rate:
    name: "High Win Rate"
    description: "High probability setups with tight risk control"
    instruments: ["EUR_USD", "GBP_USD", "XAU_USD"]
    risk_settings:
      max_risk_per_trade: 0.015
      max_portfolio_risk: 0.40
      daily_trade_limit: 40
      max_positions: 2
    target_performance:
      sharpe: 38.85
      win_rate: 82.4
      annual_return: 113.9

  high_frequency:
    name: "High Frequency"
    description: "Multiple small trades with quick profits"
    instruments: ["EUR_USD", "GBP_USD", "XAU_USD"]
    risk_settings:
      max_risk_per_trade: 0.01
      max_portfolio_risk: 0.40
      daily_trade_limit: 30
      max_positions: 2
    target_performance:
      sharpe: 38.5
      win_rate: 79.7
      annual_return: 148.0

  gold_trump_week:
    name: "Gold Trump Week"
    description: "Gold specialist with fundamental analysis"
    instruments: ["XAU_USD", "EUR_USD", "GBP_USD"]  # Gold first!
    risk_settings:
      max_risk_per_trade: 0.015
      max_portfolio_risk: 0.50
      daily_trade_limit: 40
      max_positions: 3
    target_performance:
      sharpe: 2.5
      win_rate: 65.0
      annual_return: 150.0

# =============================================================================
# ACCOUNT MAPPING - SINGLE SOURCE OF TRUTH
# =============================================================================
accounts:
  - id: "101-004-30719775-011"
    name: "Momentum Trading"
    strategy: "momentum_trading"
    active: true
    
  - id: "101-004-30719775-007"
    name: "Zero Drawdown"
    strategy: "zero_drawdown"
    active: true
    
  - id: "101-004-30719775-006"
    name: "High Win Rate"
    strategy: "high_win_rate"
    active: true
    
  - id: "101-004-30719775-008"
    name: "High Frequency"
    strategy: "high_frequency"
    active: true
    
  - id: "101-004-30719775-001"
    name: "Gold Trump Week"
    strategy: "gold_trump_week"
    active: true

# =============================================================================
# CONFIGURATION VALIDATION RULES
# =============================================================================
validation:
  max_portfolio_risk_limit: 0.50  # Never exceed 50%
  min_risk_per_trade: 0.005       # Never less than 0.5%
  max_risk_per_trade: 0.02        # Never more than 2%
  required_instruments: ["EUR_USD", "GBP_USD", "XAU_USD"]
  forbidden_combinations: []
