# ===============================================
# ULTRA CONSERVATIVE TRADING STRATEGY CONFIG
# MAXIMUM 10 TRADES PER DAY TOTAL - NO FORCED TRADING
# ===============================================

# OANDA Trading API Configuration
oanda:
  api_key: "c01de9eb4d793c945ea0fcbb0620cc4e-d0c62eb93ed53e8db5a709089460794a"
  environment: "practice"
  base_url: "https://api-fxpractice.oanda.com"
  
  # Account Configuration
  accounts:
    primary: "101-004-30719775-009"    # Ultra Strict Forex
    gold_scalp: "101-004-30719775-010" # Gold Scalping  
    alpha: "101-004-30719775-011"      # Momentum Trading

# Strategy Mapping
strategy_mapping:
  primary: "ultra_strict_forex"
  gold_scalp: "gold_scalping"
  alpha: "momentum_trading"

# ===============================================
# ULTRA CONSERVATIVE RISK MANAGEMENT
# ===============================================

risk_management:
  # Primary Account (Ultra Strict Forex) - MAX 3/DAY
  primary:
    max_risk_per_trade: 0.02
    max_portfolio_risk: 0.75
    max_positions: 5
    daily_trade_limit: 3              # ULTRA CONSERVATIVE: Max 3/day
    instruments: ["EUR_USD", "GBP_USD", "USD_JPY", "AUD_USD"]
    
  # Gold Scalping Account - MAX 4/DAY  
  gold_scalp:
    max_risk_per_trade: 0.015
    max_portfolio_risk: 0.75
    max_positions: 3
    daily_trade_limit: 4              # ULTRA CONSERVATIVE: Max 4/day
    instruments: ["XAU_USD"]
    
  # Alpha Account (Momentum Trading) - MAX 3/DAY
  alpha:
    max_risk_per_trade: 0.025
    max_portfolio_risk: 0.75
    max_positions: 7
    daily_trade_limit: 3              # ULTRA CONSERVATIVE: Max 3/day
    instruments: ["EUR_USD", "GBP_USD", "USD_JPY", "AUD_USD", "USD_CAD", "NZD_USD", "EUR_JPY", "GBP_JPY", "AUD_JPY"]

# ===============================================
# ULTRA CONSERVATIVE STRATEGY PARAMETERS
# ===============================================

strategies:
  ultra_strict_forex:
    name: "Ultra Strict Forex"
    max_trades_per_day: 3             # ULTRA CONSERVATIVE: Max 3/day
    min_trades_today: 0               # NO FORCED TRADES EVER
    
    # Ultra Conservative R:R Ratios
    stop_loss_pct: 0.003              # ULTRA TIGHT: 0.3% stop
    take_profit_pct: 0.015            # CONSERVATIVE: 1.5% target
    # R:R = 1:5.0 (ULTRA CONSERVATIVE)
    
    # Ultra High Signal Quality
    min_signal_strength: 0.90         # ULTRA HIGH: Only perfect setups
    quality_score_threshold: 0.95     # ULTRA HIGH: Only flawless setups
    max_daily_quality_trades: 1       # Only TOP 1 per day
    
    # EMA Parameters
    ema_periods: [3, 8, 21]
    
    # Ultra Selective Entry Filters
    require_trend_alignment: true
    trend_timeframes: ["5M", "15M", "1H", "4H"]  # ALL must align
    trend_strength_min: 0.8                      # Ultra strong trend
    only_trade_london_ny_overlap: true           # Only overlap period
    min_volatility_threshold: 0.0001             # Ultra high volatility
    max_spread_threshold: 0.5                    # Ultra tight spreads
    require_volume_confirmation: true            # Volume must confirm
    require_news_alignment: true                 # News must align

  gold_scalping:
    name: "Gold Scalping"
    max_trades_per_day: 4             # ULTRA CONSERVATIVE: Max 4/day
    min_trades_today: 0               # NO FORCED TRADES EVER
    
    # Ultra Conservative R:R Ratios
    stop_loss_pips: 5                 # ULTRA TIGHT: 5 pips stop
    take_profit_pips: 20              # CONSERVATIVE: 20 pips target
    # R:R = 1:4.0 (ULTRA CONSERVATIVE)
    
    # Ultra High Signal Quality
    min_signal_strength: 0.90         # ULTRA HIGH: Only perfect setups
    quality_score_threshold: 0.95     # ULTRA HIGH: Only flawless setups
    max_daily_quality_trades: 1       # Only TOP 1 per day
    
    # Ultra Selective Entry Filters
    require_pullback: true
    pullback_ema_period: 21           # Must pull back to 21 EMA
    only_trade_london_ny_overlap: true  # Only overlap period
    min_time_between_trades_minutes: 60  # Increased spacing
    min_volatility: 0.0001            # Ultra high volatility
    max_spread: 0.5                   # Ultra tight spreads
    min_atr_for_entry: 2.0            # Higher ATR required
    require_volume_confirmation: true  # Volume must confirm
    require_news_alignment: true      # News must align
    
    # Breakout Parameters
    breakout_lookback: 15
    breakout_threshold: 0.004         # 0.4% move - VERY STRONG only

  momentum_trading:
    name: "Momentum Trading"
    max_trades_per_day: 3             # ULTRA CONSERVATIVE: Max 3/day
    min_trades_today: 0               # NO FORCED TRADES EVER
    
    # Ultra Conservative R:R Ratios
    stop_loss_atr: 1.0                # ULTRA TIGHT: 1.0 ATR stop
    take_profit_atr: 5.0              # CONSERVATIVE: 5.0 ATR target
    # R:R = 1:5.0 (ULTRA CONSERVATIVE)
    
    # Ultra High Signal Quality
    min_adx: 30                       # ULTRA HIGH: Only very strong trends
    min_momentum: 0.40                # ULTRA HIGH: Only strong momentum
    min_volume: 0.35                  # ULTRA HIGH: Only high volume
    quality_score_threshold: 0.95     # ULTRA HIGH: Only flawless setups
    max_daily_quality_trades: 1       # Only TOP 1 per day
    
    # Technical Parameters
    momentum_period: 14
    volume_period: 20
    atr_period: 14
    adx_period: 14
    
    # Ultra Selective Entry Filters
    require_trend_alignment: true
    trend_timeframes: ["5M", "15M", "1H", "4H"]  # ALL must align
    trend_strength_min: 0.8                      # Ultra strong trend
    only_trade_london_ny_overlap: true           # Only overlap period
    min_volatility_threshold: 0.0001             # Ultra high volatility
    max_spread_threshold: 0.5                    # Ultra tight spreads
    require_volume_confirmation: true            # Volume must confirm
    require_news_alignment: true                 # News must align

# ===============================================
# ULTRA QUICK EARLY CLOSURE SYSTEM
# ===============================================

early_closure:
  profit_pct: 0.001                   # Close at +0.1% profit
  loss_pct: -0.002                    # Close at -0.2% loss
  max_hold_time_minutes: 30           # ULTRA QUICK: 30 min max
  trailing_stop_enabled: true
  trailing_stop_distance: 0.0005      # ULTRA TIGHT: 0.05%
  
  # Trailing Stop Activation
  trailing_stop_activation_profit: 0.0005  # Start trailing after +0.05%

# ===============================================
# ULTRA SELECTIVE QUALITY FILTERS
# ===============================================

quality_filters:
  max_daily_quality_trades: 1         # Only TOP 1 per strategy per day
  min_signal_strength: 0.90           # ULTRA HIGH - only perfect setups
  quality_score_threshold: 0.95       # ULTRA HIGH - only flawless setups
  daily_trade_ranking: true           # Rank and select ONLY the best
  ultra_selective_mode: true          # Ultra selective trading mode
  
  # Multi-Confirmation Requirements
  require_multiple_confirmations: true
  confirmation_sources: ["technical", "volume", "news", "sentiment"]
  min_confirmations: 3                # At least 3 sources must confirm

# ===============================================
# ULTRA SELECTIVE SESSION SETTINGS
# ===============================================

trading_sessions:
  only_trade_london_ny_overlap: true  # Only 13:00-16:00 UTC overlap
  london_ny_overlap_start: 13         # 13:00 UTC
  london_ny_overlap_end: 16           # 16:00 UTC
  
  # Session Filters
  london_session_start: 7             # 07:00 UTC
  london_session_end: 16              # 16:00 UTC
  ny_session_start: 13                # 13:00 UTC
  ny_session_end: 21                  # 21:00 UTC
  asia_session_start: 21              # 21:00 UTC
  asia_session_end: 7                 # 07:00 UTC (next day)

# ===============================================
# ULTRA HIGH VOLATILITY & SPREAD FILTERS
# ===============================================

market_conditions:
  min_volatility_threshold: 0.0001    # Ultra high volatility required
  max_spread_threshold: 0.5           # Ultra tight spreads only
  
  # Volatility Settings
  volatility_period: 20
  volatility_multiplier: 2.0          # 2x average volatility required
  
  # Spread Settings
  max_spread_pips: 0.5                # Maximum spread in pips
  spread_check_frequency: 60          # Check spreads every 60 seconds

# ===============================================
# NEWS INTEGRATION - ULTRA SELECTIVE
# ===============================================

news_integration:
  enabled: true
  require_news_alignment: true        # News must align with trade
  min_news_sentiment: 0.7            # Strong news sentiment required
  avoid_high_impact_events: true     # Avoid all high impact events
  
  # News Sources
  sources: ["alpha_vantage", "marketaux", "newsdata", "newsapi"]
  
  # News Filtering
  high_impact_keywords: ["Fed", "FOMC", "NFP", "CPI", "GDP", "rates", "inflation"]
  pause_trading_on_high_impact: true
  resume_trading_after_minutes: 30   # Resume 30 minutes after high impact

# ===============================================
# TELEGRAM NOTIFICATIONS
# ===============================================

notifications:
  telegram:
    enabled: true
    token: "7248728383:AAEE7lkAAIUXBcK9iTPR5NIeTq3Aqbyx6IU"
    chat_id: "6100678501"
    
    # Notification Settings
    notify_on_trade_entry: true
    notify_on_trade_exit: true
    notify_on_early_close: true
    notify_daily_summary: true
    notify_system_alerts: true
    
    # Message Templates
    trade_entry_template: "🎯 ULTRA SELECTIVE ENTRY: {strategy} {instrument} {side} at {price} (Confidence: {confidence:.2f})"
    trade_exit_template: "✅ ULTRA QUICK EXIT: {strategy} {instrument} {side} - P&L: {pnl:.2f} ({reason})"
    daily_summary_template: "📊 ULTRA CONSERVATIVE DAILY SUMMARY: {total_trades} trades, P&L: {total_pnl:.2f}"

# ===============================================
# DATA VALIDATION SETTINGS
# ===============================================

data_validation:
  max_data_age_seconds: 300           # 5 minutes max data age
  min_confidence_threshold: 0.9       # Ultra high confidence required
  require_live_data: true             # Live data only
  
  # Data Quality Checks
  price_deviation_threshold: 0.001    # Max 0.1% price deviation
  volume_spike_threshold: 3.0         # 3x average volume spike
  spread_anomaly_threshold: 2.0       # 2x normal spread

# ===============================================
# SYSTEM PERFORMANCE SETTINGS
# ===============================================

performance:
  dashboard_update_interval: 15       # 15 seconds
  market_data_update_interval: 5      # 5 seconds
  system_status_check_interval: 30    # 30 seconds
  
  # Memory Management
  max_price_history_bars: 1000        # Limit price history
  max_signal_history: 100             # Limit signal history
  cleanup_interval_minutes: 60        # Cleanup every hour

# ===============================================
# LOGGING CONFIGURATION
# ===============================================

logging:
  level: "INFO"
  enable_structured_logging: true
  
  # Log Files
  trade_log: "logs/ultra_conservative_trades.log"
  system_log: "logs/ultra_conservative_system.log"
  error_log: "logs/ultra_conservative_errors.log"
  
  # Log Rotation
  max_file_size: "10MB"
  backup_count: 5

# ===============================================
# SECURITY SETTINGS
# ===============================================

security:
  api_rate_limit: 100                 # 100 requests per window
  api_rate_window: 60                 # 60 second window
  cors_origins: "*"                   # CORS settings
  
  # Authentication
  require_api_key: true
  api_key_header: "X-API-Key"
  
  # Rate Limiting
  requests_per_minute: 60
  burst_limit: 10

# ===============================================
# ULTRA CONSERVATIVE SUMMARY
# ===============================================

summary:
  total_max_trades_per_day: 10        # MAXIMUM 10 TRADES PER DAY TOTAL
  no_forced_trading: true             # NO FORCED TRADES EVER
  ultra_quality_focus: true           # Only perfect setups
  ultra_quick_exits: true             # 30 minute max hold
  ultra_selective_entries: true       # Multi-timeframe + news alignment
  
  expected_improvements:
    trade_reduction: "95-97%"         # From 180-400 to 0-10 trades/day
    rr_improvement: "25-50%"          # 1:4.0 to 1:5.0 ratios
    quality_improvement: "28%"        # 0.70 to 0.90 signal strength
    risk_reduction: "90%"             # Ultra tight stops and quick exits
