ultra_strict_forex:
  locked: false
  enabled: true
  account: '010'
  parameters:
    max_trades_per_day: 999
    min_trades_today: 0
    max_positions: 50
    lot_size: 25000
  entry:
    confidence_threshold: 0.25
    min_adx: 15
    min_momentum: 0.3
    use_news: true
  risk:
    stop_loss_pct: 0.005
    take_profit_pct: 0.008
    max_risk_per_trade: 0.015
  instruments:
  - XAU_USD
  - EUR_USD
  - GBP_USD
  - USD_JPY
  - AUD_USD
  - USD_CAD
  - NZD_USD
gold_scalping:
  locked: false
  enabled: true
  account: 009
  parameters:
    max_trades_per_day: 20
    min_trades_today: 0
    max_positions: 3
    lot_size: 10000
    min_warmup_prices: 2
  entry:
    confidence_threshold: 0.35
    min_momentum: 0.005
    use_volume: true
  risk:
    stop_loss_pct: 0.003
    take_profit_pct: 0.005
    max_risk_per_trade: 0.02
  instruments:
  - XAU_USD
momentum_trading:
  locked: false
  enabled: true
  account: '011'
  
  # ADAPTIVE SETTINGS (NEW OCT 16, 2025)
  adaptive_mode: true              # Enable regime detection & adaptive thresholds
  target_trades_per_day: 5         # Soft target (~5 trades/day, OK with 0-10)
  max_trades_per_day: 10           # Hard limit
  min_trades_today: 0              # NO forced trades - quality over quantity
  
  parameters:
    max_positions: 3               # Concentrate capital on best setups
    lot_size: 50000                # Bigger positions on elite setups
  
  # BASE THRESHOLDS (adjusted by regime)
  entry:
    base_quality_threshold: 70     # Trending: 60, Ranging: 80, Choppy: 90
    base_confidence: 0.65          # Will adapt based on market regime
    base_momentum: 0.008           # 0.8% baseline (adapts to 0.6%-1.0%)
    min_adx: 25                    # For trend detection
    min_volume: 0.35               # Above-average volume
    use_news: true
  
  # PROFIT PROTECTION (NEW OCT 16, 2025)
  profit_protection:
    breakeven_at: 0.005            # +0.5% profit → move to break-even
    trail_at: 0.015                # +1.5% profit → activate trailing stop
    trail_distance: 0.008          # Trail 0.8% behind peak
  
  # SNIPER ENTRIES (NEW OCT 16, 2025)
  sniper_mode: true                # Enable pullback entries in trends
  sniper_ema_period: 20            # EMA for pullback detection
  sniper_tolerance: 0.002          # 0.2% proximity to EMA
  
  risk:
    stop_loss_pct: 0.008           # Initial SL (-0.8%)
    take_profit_pct: 0.024         # 3:1 R:R ratio (+2.4%)
    max_risk_per_trade: 0.02       # 2% max risk per trade
  instruments:
  - XAU_USD
  - EUR_USD
  - GBP_USD
  - USD_JPY
  - AUD_USD
  - USD_CAD
  - NZD_USD
system:
  capacity: 0.75
  telegram_alerts: true
  log_all_changes: true
  deployment: google-cloud

