# TOP 3 OPTIMIZED STRATEGIES - LIVE DEPLOYMENT CONFIGURATION
# Deployed: October 2, 2025
# Accounts: 3 OANDA Demo Accounts
# Strategies: Top 3 from optimization_20251002_195254

accounts:
  # ACCOUNT 1: Strategy #1 - BEST SHARPE RATIO (35.90)
  - id: "demo_001"
    name: "TOP_STRATEGY_1_CHAMPION"
    account_id: "101-004-30719775-008"
    strategy: "gbp_usd_5m_strategy_rank_1"
    instruments: ["GBP_USD"]
    priority: 1
    risk_settings:
      max_risk_per_trade: 0.015  # 1.5% per trade
      max_positions: 5
      max_daily_trades: 100
      portfolio_risk_limit: 0.10  # 10% total exposure
      stop_loss_multiplier: 1.5   # 1.5x ATR
      take_profit_ratio: 3.0      # 1:3 Risk:Reward
    strategy_params:
      ema_fast_period: 3
      ema_slow_period: 12
      rsi_period: 14
      rsi_oversold: 20
      rsi_overbought: 80
      atr_period: 14
      atr_multiplier: 1.5
      timeframe: "5m"
    performance_targets:
      target_sharpe: 35.90
      target_win_rate: 80.3
      target_annual_return: 110.6
      max_drawdown_limit: 0.006  # 0.6%
    trading_sessions:
      enabled_hours:
        - "08:00-12:00 UTC"  # London Open
        - "13:00-17:00 UTC"  # London/NY Overlap  
        - "17:00-20:00 UTC"  # NY Afternoon
      disabled_hours:
        - "00:00-08:00 UTC"  # Asian Session
        - "20:00-24:00 UTC"  # Late NY

  # ACCOUNT 2: Strategy #2 - SECOND BEST (35.55)
  - id: "demo_002" 
    name: "TOP_STRATEGY_2_EXCELLENT"
    account_id: "101-004-30719775-007"
    strategy: "gbp_usd_5m_strategy_rank_2"
    instruments: ["GBP_USD"]
    priority: 2
    risk_settings:
      max_risk_per_trade: 0.015  # 1.5% per trade
      max_positions: 5
      max_daily_trades: 100
      portfolio_risk_limit: 0.10  # 10% total exposure
      stop_loss_multiplier: 1.5   # 1.5x ATR
      take_profit_ratio: 3.0      # 1:3 Risk:Reward
    strategy_params:
      ema_fast_period: 3
      ema_slow_period: 12
      rsi_period: 14
      rsi_oversold: 25  # Slightly more conservative
      rsi_overbought: 80
      atr_period: 14
      atr_multiplier: 1.5
      timeframe: "5m"
    performance_targets:
      target_sharpe: 35.55
      target_win_rate: 80.1
      target_annual_return: 110.5
      max_drawdown_limit: 0.006  # 0.6%
    trading_sessions:
      enabled_hours:
        - "08:00-12:00 UTC"  # London Open
        - "13:00-17:00 UTC"  # London/NY Overlap
        - "17:00-20:00 UTC"  # NY Afternoon
      disabled_hours:
        - "00:00-08:00 UTC"  # Asian Session
        - "20:00-24:00 UTC"  # Late NY

  # ACCOUNT 3: Strategy #3 - THIRD BEST (35.18) - LOWEST DRAWDOWN
  - id: "demo_003"
    name: "TOP_STRATEGY_3_CONSERVATIVE" 
    account_id: "101-004-30719775-006"
    strategy: "gbp_usd_5m_strategy_rank_3"
    instruments: ["GBP_USD"]
    priority: 3
    risk_settings:
      max_risk_per_trade: 0.015  # 1.5% per trade
      max_positions: 5
      max_daily_trades: 100
      portfolio_risk_limit: 0.10  # 10% total exposure
      stop_loss_multiplier: 1.5   # 1.5x ATR
      take_profit_ratio: 3.0      # 1:3 Risk:Reward
    strategy_params:
      ema_fast_period: 3
      ema_slow_period: 12
      rsi_period: 14
      rsi_oversold: 30  # Most conservative
      rsi_overbought: 80
      atr_period: 14
      atr_multiplier: 1.5
      timeframe: "5m"
    performance_targets:
      target_sharpe: 35.18
      target_win_rate: 79.8
      target_annual_return: 109.1
      max_drawdown_limit: 0.004  # 0.4% - LOWEST
    trading_sessions:
      enabled_hours:
        - "08:00-12:00 UTC"  # London Morning
        - "13:00-17:00 UTC"  # Peak liquidity
        - "13:00-20:00 UTC"  # NY Session
      disabled_hours:
        - "00:00-08:00 UTC"  # Low liquidity

# STRATEGY DEFINITIONS
strategies:
  gbp_usd_5m_strategy_rank_1:
    class_name: "GBP_USD_5m_Strategy_Rank_1"
    module: "src.strategies.gbp_usd_optimized"
    function: "get_strategy_rank_1"
    description: "Best performing strategy with 35.90 Sharpe ratio and 80.3% win rate"
    best_for: "Maximum Sharpe ratio, aggressive growth"
    timeframe: "5m"
    
  gbp_usd_5m_strategy_rank_2:
    class_name: "GBP_USD_5m_Strategy_Rank_2" 
    module: "src.strategies.gbp_usd_optimized"
    function: "get_strategy_rank_2"
    description: "Second best with 35.55 Sharpe ratio and 80.1% win rate"
    best_for: "High performance with slight conservatism"
    timeframe: "5m"
    
  gbp_usd_5m_strategy_rank_3:
    class_name: "GBP_USD_5m_Strategy_Rank_3"
    module: "src.strategies.gbp_usd_optimized" 
    function: "get_strategy_rank_3"
    description: "Third best with 35.18 Sharpe ratio and 79.8% win rate, lowest drawdown"
    best_for: "Conservative approach with minimal drawdown"
    timeframe: "5m"

# GLOBAL SETTINGS
global_settings:
  data_feed: "oanda_live"
  environment: "demo"
  risk_management: "strict"
  max_total_exposure: 0.30  # 30% across all accounts
  emergency_stop_loss: 0.15  # 15% total portfolio loss
  daily_loss_limit: 0.05    # 5% daily loss limit
  telegram_alerts: true
  dashboard_monitoring: true
  auto_scaling: false  # Manual scaling only
  news_integration: true
  session_filtering: true
  
# PERFORMANCE TARGETS (Combined)
combined_targets:
  total_sharpe: 35.5
  total_win_rate: 80.0
  total_annual_return: 110.0
  max_combined_drawdown: 0.005  # 0.5%
  total_trades_per_day: 300     # 100 per account
  profit_factor_target: 20.0
  
# MONITORING & ALERTS
monitoring:
  performance_check_interval: 300  # 5 minutes
  risk_check_interval: 60          # 1 minute
  telegram_alerts:
    trade_execution: true
    daily_summary: true
    risk_warnings: true
    performance_updates: true
  dashboard_updates: 15            # 15 seconds
  log_level: "INFO"
  
# DEPLOYMENT NOTES
deployment_notes:
  - "All 3 strategies tested on 3+ years of real OANDA data"
  - "Total backtest trades: 9,642 across all strategies"
  - "Expected combined daily trades: 200-300"
  - "Best trading hours: 13:00-17:00 UTC (London/NY overlap)"
  - "Avoid trading: 00:00-08:00 UTC (Asian session)"
  - "Risk management: 1.5% per trade, 10% portfolio limit"
  - "Target: 110% annual return with <1% max drawdown"
